<?php
/**
 * @file
 * Code for the Drupal Cebu Meetup API feature.
 */

include_once 'drupalcebu_meetup_api.features.inc';

/**
* Implements hook_block_info().
*/
function drupalcebu_meetup_api_block_info() {
  $blocks = array();
  $blocks['meetup_upcoming'] = array(
    'info' => t('Upcoming Meetups'),
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function drupalcebu_meetup_api_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'meetup_upcoming':
      $block['subject'] = '';
      $block['content'] = _drupalcebu_meetup_api_block_content();
      break;
  }
  return $block;
}

function _drupalcebu_meetup_api_block_content() {
  $group = variable_get('drupalcebu_group_urlname', 'drupal-ph');
  $request = array(
    'group_urlname' => $group, 
    'order' => 'time',
  );
  $options = array('pages' => 1); 
  $result = meetup_api_events($request, $options);
  if (!empty($result->results) && is_array($result->results)) {
    $title = t('Upcoming ') . t($result->meta->title);
    $type = 'ul';
    $attributes = array(
      'class' => 'meetup-list',
    );

    $items = array();
    foreach($result->results as $event) {
      $event_info = '<h2 class="meetup-event">' . $event->name . '</h2>';
      if (!empty($event->venue_name) && !empty($event->venue_address1)) {
      	$event_info .= '<div class="meetup-venue"><div class="label">Venue:</div> ' . $event->venue_name . (!empty($event->venue_address1) ? ' (' . $event->venue_address1 . ')' : '') . '</div>';
      }
      $event_info .= '<div class="meetup-date"><div class="label">Date:</div>' . format_date(strtotime($event->time), 'medium') . '</div>';
      $link = 'http://www.meetup.com/'. $group .'/quick_join/?eventId='. $event->id .'&joinFrom=event&response=3';
     $event_info .= '<div class="meetup-join">' . l(t('Join Meetup'), $link) . '</div>';
      $items[] = array(
        'data' => $event_info,
        'id' => 'meetup-event-' . $event->id,
        'class' => array('meetup-list-item'),
      );
    }

    return theme_item_list(
      array(
        'items' => $items,
        'title' => $title,
        'type' => $type,
        'attributes' => $attributes
      )
    );
  }
  return FALSE;
}
