<?php
/**
 * @file
 * Code for simple date type and format module.
 */

/**
 * Implements hook_date_formats().
 */
function drupalcebu_simple_date_type_date_formats() {
  return array(
    // Creates a new format for a new, custom format type called simple.
    array(
      'type' => 'simple',
      'format' => 'F j, Y',
      'locales' => array(),
    ),
  );
}

/**
 * Implements hook_date_format_types().
 */
function drupalcebu_simple_date_type_date_format_types() {
  return array(
    'simple' => t('Simple'),
  );
}
